### ISSUE TITLE
Location oddity

### ISSUE THREAD

**Issue by SlimeDog** [FancyMcPlugins/FancyHolograms#54]
Paper 1.20.4-328
FancyHolograms 2.0.4-b35

With the holograms shown below, most of the BLOCK holograms are at
```
      y: 5.5
```
All are on the same horizontal plane visually, except for the last one (lobby-yellowdog-block), which has to be at
```
      y: 5.400000095367432
```
to achieve the same plane. Any idea why?

```
holograms:
  lobby-playground:
    type: TEXT
    location:
      world: world_lobby
      x: 134.0
      y: 4.5
      z: 130.5
      yaw: 0.0
      pitch: 0.0
    scale_x: 1.0
    scale_y: 1.0
    scale_z: 1.0
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    text:
    - <#3E61AB><bold>PLAYGROUND</bold></#3E61AB>
    - '&r'
    - '&r'
    - <#3E61AB>CREATIVE</#3E61AB>
    - <#3E61AB>EASY</#3E61AB>
    - <dark_red>START HERE</dark_red>
    text_shadow: false
    text_alignment: center
    update_text_interval: -1
    billboard: fixed
    background: transparent
  lobby-playground-block:
    type: BLOCK
    location:
      world: world_lobby
      x: 133.875
      y: 5.400000095367432
      z: 130.625
      yaw: 0.0
      pitch: 0.0
    scale_x: 0.25
    scale_y: 0.25
    scale_z: 0.25
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: vertical
    block: LAPIS_ORE
  lobby-blackdog:
    type: TEXT
    location:
      world: world_lobby
      x: 139.0
      y: 4.5
      z: 130.5
      yaw: 0.0
      pitch: 0.0
    scale_x: 1.0
    scale_y: 1.0
    scale_z: 1.0
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: fixed
    text:
    - <#2D2C29><bold>BLACKDOG</bold></#2D2C29>
    - '&r'
    - '&r'
    - <#2D2C29>SURVIVAL</#2D2C29>
    - <#2D2C29>HARD</#2D2C29>
    - <dark_gray>%server_online_world_blackdog% players</dark_gray>
    text_shadow: false
    text_alignment: center
    update_text_interval: -1
    background: transparent
  lobby-blackdog-block:
    type: BLOCK
    location:
      world: world_lobby
      x: 138.875
      y: 5.400000095367432
      z: 130.625
      yaw: 0.0
      pitch: 0.0
    scale_x: 0.25
    scale_y: 0.25
    scale_z: 0.25
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: vertical
    block: COAL_ORE
  lobby-luckyblock:
    type: TEXT
    location:
      world: world_lobby
      x: 142.25
      y: 4.5
      z: 134.0
      yaw: 90.0
      pitch: 0.0
    scale_x: 1.0
    scale_y: 1.0
    scale_z: 1.0
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: fixed
    text:
    - <#6F5736><bold>LUCKYBLOCK</bold></#6F5736>
    - '&r'
    - '&r'
    - <#6F5736>SOME GOOD</#6F5736>
    - <#6F5736>SOME BAD</#6F5736>
    - <dark_gray>%server_online_world_luckyblock% players</dark_gray>
    text_shadow: false
    text_alignment: center
    update_text_interval: -1
    background: transparent
  lobby-luckyblock-block:
    type: BLOCK
    location:
      world: world_lobby
      x: 142.375
      y: 5.400000095367432
      z: 133.875
      yaw: 0.0
      pitch: 0.0
    scale_x: 0.25
    scale_y: 0.25
    scale_z: 0.25
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: vertical
    block: RAW_IRON_BLOCK
  lobby-skyblock:
    type: TEXT
    location:
      world: world_lobby
      x: 142.25
      y: 4.5
      z: 139.0
      yaw: 90.0
      pitch: 0.0
    scale_x: 1.0
    scale_y: 1.0
    scale_z: 1.0
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: fixed
    text:
    - <#47A783><bold>SKYBLOCK</bold></#47A783>
    - '&r'
    - '&r'
    - <#47A783>ISLANDS</#47A783>
    - <#47A783>CHALLENGES</#47A783>
    - <dark_gray>%server_online_world_skyblock% players</dark_gray>
    text_shadow: false
    text_alignment: center
    update_text_interval: -1
    background: transparent
  lobby-skyblock-block:
    type: BLOCK
    location:
      world: world_lobby
      x: 142.375
      y: 5.400000095367432
      z: 138.875
      yaw: 0.0
      pitch: 0.0
    scale_x: 0.25
    scale_y: 0.25
    scale_z: 0.25
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: vertical
    block: COPPER_ORE
  lobby-westeros:
    type: TEXT
    location:
      world: world_lobby
      x: 139.0
      y: 4.5
      z: 142.25
      yaw: 180.0
      pitch: 0.0
    scale_x: 1.0
    scale_y: 1.0
    scale_z: 1.0
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: fixed
    text:
    - <#880605><bold>WESTEROS</bold></#880605>
    - '&r'
    - '&r'
    - <#880605>ADVENTURE</#880605>
    - <#880605>PEACEFUL</#880605>
    - <dark_gray>%server_online_world_westeros% players</dark_gray>
    text_shadow: false
    text_alignment: center
    update_text_interval: -1
    background: transparent
  lobby-westeros-block:
    type: BLOCK
    location:
      world: world_lobby
      x: 139.125
      y: 5.400000095367432
      z: 142.375
      yaw: 0.0
      pitch: 0.0
    scale_x: 0.25
    scale_y: 0.25
    scale_z: 0.25
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: vertical
    block: REDSTONE_ORE
  lobby-city:
    type: TEXT
    location:
      world: world_lobby
      x: 134.0
      y: 4.5
      z: 142.25
      yaw: 180.0
      pitch: 0.0
    scale_x: 1.0
    scale_y: 1.0
    scale_z: 1.0
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: fixed
    text:
    - <#C59A71><bold>THE CITY</bold></#C59A71>
    - '&r'
    - '&r'
    - <#C59A71>SURVIVAL</#C59A71>
    - <#C59A71>HARD</#C59A71>
    - <dark_gray>%server_online_world_city% players</dark_gray>
    text_shadow: false
    text_alignment: center
    update_text_interval: -1
    background: transparent
  lobby-city-block:
    type: BLOCK
    location:
      world: world_lobby
      x: 134.125
      y: 5.400000095367432
      z: 142.375
      yaw: 0.0
      pitch: 0.0
    scale_x: 0.25
    scale_y: 0.25
    scale_z: 0.25
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: vertical
    block: IRON_ORE
  lobby-whitedog:
    type: TEXT
    location:
      world: world_lobby
      x: 130.75
      y: 4.5
      z: 139.0
      yaw: -90.0
      pitch: 0.0
    scale_x: 1.0
    scale_y: 1.0
    scale_z: 1.0
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: fixed
    text:
    - <#1DC7C1><bold>WHITEDOG</bold></#1DC7C1>
    - '&r'
    - '&r'
    - <#1DC7C1>SURVIVAL</#1DC7C1>
    - <#1DC7C1>EXTRA HARD</#1DC7C1>
    - <dark_gray>%server_online_world_whitedog% players</dark_gray>
    text_shadow: false
    text_alignment: center
    update_text_interval: -1
    background: transparent
  lobby-whitedog-block:
    type: BLOCK
    location:
      world: world_lobby
      x: 130.625
      y: 5.400000095367432
      z: 139.125
      yaw: 0.0
      pitch: 0.0
    scale_x: 0.25
    scale_y: 0.25
    scale_z: 0.25
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: vertical
    block: DIAMOND_ORE
  lobby-yellowdog:
    type: TEXT
    location:
      world: world_lobby
      x: 130.75
      y: 4.599999904632568
      z: 134.0
    scale_y: 1.0
    scale_z: 1.0
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: fixed
    text:
    - <#1DC7C1><bold>WHITEDOG</bold></#1DC7C1>
    - '&r'
    - '&r'
    - <#1DC7C1>SURVIVAL</#1DC7C1>
    - <#1DC7C1>EXTRA HARD</#1DC7C1>
    - <dark_gray>%server_online_world_whitedog% players</dark_gray>
    text_shadow: false
    text_alignment: center
    update_text_interval: -1
    background: transparent
  lobby-whitedog-block:
    type: BLOCK
    location:
      world: world_lobby
      x: 130.625
      y: 5.400000095367432
      z: 139.125
      yaw: 0.0
      pitch: 0.0
    scale_x: 0.25
    scale_y: 0.25
    scale_z: 0.25
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: vertical
    block: DIAMOND_ORE
  lobby-yellowdog:
    type: TEXT
    location:
      world: world_lobby
      x: 130.75
      y: 4.599999904632568
      z: 134.0
      yaw: -90.0
      pitch: 0.0
    scale_x: 1.0
    scale_y: 1.0
    scale_z: 1.0
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: fixed
    text:
    - <#E3D43F><bold>WHITEDOG</bold></#E3D43F>
    - '&r'
    - '&r'
    - <#E3D43F>SURVIVAL</#E3D43F>
    - <#E3D43F>EXTRA HARD</#E3D43F>
    - <dark_gray>%server_online_world_yellowdog% players</dark_gray>
    text_shadow: false
    text_alignment: center
    update_text_interval: -1
    background: transparent
  lobby-yellowdog-block:
    type: BLOCK
    location:
      world: world_lobby
      x: 130.625
      y: 5.5
      z: 134.125
      yaw: 0.0
      pitch: 0.0
    scale_x: 0.25
    scale_y: 0.25
    scale_z: 0.25
    shadow_radius: 0.0
    shadow_strength: 1.0
    visibility_distance: 20
    billboard: vertical
    block: GOLD_ORE
version: 2 # DO NOT CHANGE 
```
